# Generated by Django 5.1.2 on 2024-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_url', models.URLField()),
            ],
        ),
    ]
