# Generated by Django 5.1.2 on 2024-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGscrapingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
